# 服务器相关配置
server:
  port: 8080
  servlet:
    context-path: /rainbow/sugar
    session:
      timeout: 30m
  tomcat:
    uri-encoding: UTF-8

# spring相关配置
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.192.119:3306/hty-test2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: LSPlsp123@
    # 连接池配置
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # jpa配置
  jpa:
    database: mysql # 数据库类型
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  # 数据库方言
    show-sql: false  # 打印sql语句
    hibernate:
      ddl-auto: update
    open-in-view: true  # 在事务外也可以访问懒加载的数据
    properties:
      hibernate:
        enable_lazy_load_no_trans: true # 解决 org.hibernate.LazyInitializationException: could not initialize proxy - no Session 异常
  # 日志输出配置
  output:
    ansi:
      enabled: ALWAYS

## 日志配置
#logging:
#  # 日志文件配置
#  file:
#    max-history: 10 # 日志保留天数
#    max-size: 10MB  # 日志文件大小
#  # 日志输出格式配置
#  pattern:
#    console: '[TIMEKEY=%X{timekey}] %c [%d{yyyy-MM-dd HH:mm:ss:SSS}] [%-5p] %m%n'  # 控制台输出格式
#    file: '[TIMEKEY=%X{timekey}] %c [%d{yyyy-MM-dd HH:mm:ss:SSS}] [%-5p] %m%n'     # 文件输出格式
#  # 日志级别配置
#  level:
#    com:
#      huitongyi:
#        manage:
#          appforweachat: info  # 指定该路径打印日志的级别

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml  # xml扫描，多个目录用逗号或者分号分隔
  type-aliases-package: com.huitongyi.manage.appforweachat.entity  # 实体扫描，多个package用逗号或者分号分隔
  # 全局配置
  global-config:
    # 数据库相关配置
    db-config:
      # - AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      # - 0:"数据库ID自增", 1:"用户输入ID", 2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      capital-mode: true  # 数据库大写下划线转换
      # 字段策略 IGNORED:"忽略判断", NOT_NULL:"非 NULL 判断", NOT_EMPTY:"非空判断"
      # 字段策略 0:"忽略判断", 1:"非 NULL 判断", 2:"非空判断"
      field-strategy: NOT_EMPTY
      db-type: MYSQL  # 数据库类型
  # mybatis原生配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印mybatis执行的sql语句
    map-underscore-to-camel-case: true  # 开启驼峰命名
    cache-enabled: true # 开启二级缓存
    call-setters-on-nulls: true # 如果查询结果中包含空值的列，则mybatis在映射的时候，不会映射这个字段